#
# Makefile for sensor chip drivers.
#

obj-$(CONFIG_THERMAL)			+= thermal_sys.o
obj-$(CONFIG_THERMAL_MONITOR)		+= msm_thermal.o msm_thermal-dev.o
obj-$(CONFIG_THERMAL_TSENS8974)		+= msm8974-tsens.o
obj-$(CONFIG_THERMAL_QPNP)		+= qpnp-temp-alarm.o
obj-$(CONFIG_THERMAL_QPNP_ADC_TM)	+= qpnp-adc-tm.o
